name: CI

on:
  workflow_call:

env:
  TAG: 4.0.1
  COMMIT: b64f68a94e61fa2363c598c75444482b48056697

jobs:
  download:
    runs-on: ubuntu-slim
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v7

      - name: Download
        run: ./tools/download.sh

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: source
          path: ${{ env.ARTIFACT }}
          archive: false

      - name: Upload Timestamp
        uses: actions/upload-artifact@v7
        with:
          name: timestamp
          path: TIMESTAMP
          archive: false

      - name: Generate Build Matrix
        id: matrix
        run: echo "matrix=$(./tools/matrix.sh)" >> "$GITHUB_OUTPUT"

  build:
    needs: [download]
    name: "${{ matrix.platform }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.download.outputs.matrix) }}

    defaults:
      run:
        shell: >-
          ${{ case(
            matrix.platform == 'windows', 'pwsh',
            matrix.platform == 'mingw', 'msys2 {0}',
            'bash'
          ) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      # Setup
      - name: Setup Environment
        shell: bash
        run: |
          . tools/vars.sh
          {
            echo "DIRECTORY=$DIRECTORY"
            echo "ARTIFACT=$ARTIFACT"
            echo "OUT_DIR=$GITHUB_WORKSPACE/out"
          } >> "$GITHUB_ENV"

          mkdir -p out

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.11

      - name: Setup MSYS2
        if: matrix.platform == 'mingw'
        id: msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.arch == 'amd64' && 'ucrt64' || 'clangarm64' }}
          update: true
          install: >-
            git make tar curl
          pacboy: >-
            toolchain:p

      - name: Setup MSVC
        if: matrix.platform == 'windows'
        uses: TheMrMilchmann/setup-msvc-dev@v4

      # Download + extract
      - name: Download
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.ARTIFACT }}

      - name: Download Timestamp
        uses: actions/download-artifact@v8
        with:
          name: TIMESTAMP

      - name: Disable Windows Defender
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Set-MpPreference -DisableRealtimeMonitoring $true
          Set-MpPreference -DisableBehaviorMonitoring $true
          Set-MpPreference -DisableArchiveScanning $true

      - name: Extract
        run: tar xf ${{ env.ARTIFACT}}

      - name: Configure
        shell: bash
        run: ./tools/configure.sh
        env:
          ARCH: ${{ matrix.arch }}
          PLATFORM: ${{ matrix.platform }}

      - name: Build (Windows)
        if: matrix.platform == 'Windows'
        run: |
          cd $env:DIRECTORY
          $env:CL = " /MP /DEBUG:NONE"
          nmake
          nmake install DESTDIR=$env:OUT_DIR

      - name: Build (UNIX)
        if: matrix.platform != 'Windows'
        run: |
          cd $DIRECTORY
          make -j4
          make install DESTDIR=$OUT_DIR

      - name: Package
        shell: bash
        run: ./tools/package.sh
        env:
          ARCH: ${{ matrix.arch }}
          PLATFORM: ${{ matrix.platform }}

      - name: Upload Tarball
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}
          path: artifacts/*.tar.zst
          archive: false

      - name: Upload Sum
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-sha512sum
          path: artifacts/*.tar.zst.sha512sum
          archive: false